### ISSUE TITLE
v31 branch won't build on Python 3.1.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [schanjr/pyodbc#132]
```
When building v31 branch for Python 3.1.2 on Mac OS X 10.5.8, the following 
error occurs:

mkleehammer-pyodbc-3d7ddc4/src/row.cpp:337: error: invalid conversion from 
‘PyObject* (*)(PyObject*, Py_ssize_t, Py_ssize_t)’ to ‘void*’

This is due to changes in Python 3's PySequenceMethods type (e.g. see 
discussion at:

    http://www.mail-archive.com/cython-dev@codespeak.net/msg03385.html

Patch attached.
```

Original issue reported on code.google.com by `hengist....@gtempaccount.com` on 22 Oct 2010 at 3:28

Attachments:
- [row.diff](https://storage.googleapis.com/google-code-attachments/pyodbc/issue-132/comment-0/row.diff)
